#!/bin/bash

#get git hub details
while [ ! $AUTHENTICATED ]
do
  read -p "Enter your github username [Enter]: " USERNAME
  stty -echo
  read -p "Enter your github password [Enter]: " PASSWORD
  stty echo

  AUTH_CHECK=`exec wget -q -O - https://$USERNAME:$PASSWORD@github.com/api/v2/json/user/show --secure-protocol=auto --auth-no-challenge`

  if [ ! "$AUTH_CHECK" == ""  ] ; then
    break
  else
    echo Incorrect username/password combination
  fi
done

#generate key
ssh-keygen -t rsa -C "$USERNAME"

#install pre-requisites
sudo apt-get install git -y
sudo apt-get install ruby -y
sudo apt-get install rubygems -y
sudo apt-get install irb -y
sudo apt-get install rake -y
sudo apt-get install curl -y
sudo gem install chef --no-ri --no-rdoc


#read new keyfile
SSHFILENAME=~/.ssh/id_rsa.pub
while read line
do
SSHKEY=$line 
done < $SSHFILENAME

#post to github
curl -u"$USERNAME:$PASSWORD" -d"title=RegnersisVMKey&key=$SSHKEY" http://github.com/api/v2/json/user/key/add
