#!/bin/bash
#install with command single command
#wget http://github.com/pythonandchips/chef-vm-setup/raw/master/Install && bash Install


#get github details
while [ ! $AUTHENTICATED ]
do
  read -p "Enter your github username [Enter]: " USERNAME
  stty -echo
  read -p "Enter your github password [Enter]: " PASSWORD
  stty echo

  AUTH_CHECK=`exec wget -q -O - https://$USERNAME:$PASSWORD@github.com/api/v2/json/user/show --secure-protocol=auto --auth-no-challenge`

  if [ ! "$AUTH_CHECK" == ""  ] ; then
    break
  else
    echo Incorrect username/password combination
  fi
done

#generate key
ssh-keygen -t rsa -C "$USERNAME"

#install pre-requisites
sudo apt-get install git -y -q
sudo apt-get install ruby -y -q
sudo apt-get install rubygems -y -q
sudo apt-get install irb -y -q
sudo apt-get install rake -y -q
sudo apt-get install curl -y -q
sudo gem install chef --no-ri --no-rdoc


#read new keyfile
SSHFILENAME=~/.ssh/id_rsa.pub
while read line
do
SSHKEY=$SSHKEY$line
done < $SSHFILENAME

#post to github
curl -u "$USERNAME:$PASSWORD" -d "{\"key\": \"$SSHKEY\", \"title\": \"chef_vm_setup\"" https://api.github.com/user/keys

git clone git@github.com:Regenersis/chef-vm-setup.git /tmp/chef-vm-setup

cd /tmp/chef-vm-setup

ruby generate_dna.rb $USER $USERNAME $PASSWORD

sudo /var/lib/gems/1.8/bin/chef-solo -c /tmp/chef-vm-setup/solo.rb -j /tmp/chef-vm-setup/dna.json















